import Foundation

/// Central string table (en/ru/zh). Grows as features are added. Keys are
/// dotted namespaces, e.g. `nav.settings`, `recording.start`.
public enum LocalizedStrings {
    public static let table: [AppLanguage: [String: String]] = [
        .en: en, .ru: ru, .zh: zh
    ]

    /// Current-language lookup for non-View contexts (reads the persisted language,
    /// falls back to English then the key). Mirrors `LocaleManager.t`.
    public static func current(_ key: String) -> String {
        let lang = AppLanguage.current
        return table[lang]?[key] ?? table[.en]?[key] ?? key
    }

    static let en: [String: String] = [
        "app.name": "Ember",
        "menubar.start": "Start recording",
        "menubar.pause": "Pause recording",
        "menubar.resume": "Resume recording",
        "menubar.stop": "Stop recording",
        "menubar.settings": "Settings",
        "menubar.show": "Show Ember",
        "menubar.quit": "Quit Ember",
        "model.badge.recommended": "Recommended",
        "editor.blkH1": "Heading 1",
        "editor.blkH2": "Heading 2",
        "editor.blkH3": "Heading 3",
        "dialog.regenEdited.title": "Overwrite your edits?",
        "dialog.regenEdited.msg": "This summary was edited by hand. Regenerating replaces it with fresh AI output.",
        "models.group.russian": "Russian speech (GigaAM)",
        "models.group.multilingual": "Multilingual (Whisper)",
        "models.group.light": "Light — 1.7B",
        "models.group.standard": "Core — 4B",
        "models.group.max": "Top — 8B",
        "model.badge.balanced": "Balanced",
        "nav.home": "Home",
        "nav.meetings": "Meetings",
        "nav.settings": "Settings",
        "common.back": "Back",
        "common.continue": "Continue",
        "common.cancel": "Cancel",
        "common.done": "Done",
        "common.save": "Save",
        "common.delete": "Delete",
        "common.retry": "Retry",
        "common.dismiss": "Dismiss",
        "home.ready.title": "Ready to record",
        "home.ready.subtitle": "Start recording — the transcript appears here in real time.",
        "home.empty.title": "Record your first meeting",
        "home.empty.subtitle": "Tap to begin. Ember transcribes speech and prepares a summary — all locally.",
        "home.shortcut": "⌘R   to start",
        "recording.status": "Recording",
        "transcript.live": "Transcript · live",
        "transcript.listening": "Listening…",
        "settings.title": "Settings",
        "sidebar.search": "Search meetings",
        "sidebar.today": "Today",
        "sidebar.yesterday": "Yesterday",
        "sidebar.meetings": "Meetings",
        "sidebar.empty1": "No meetings yet.",
        "sidebar.empty2": "Start your first recording.",
        "sidebar.noResults": "Nothing found. Try a different search.",
        "meeting.exportType": "Meeting",
        "common.next": "Next",
        "common.getStarted": "Get Started",
        "onb.step": "step {n} of {t}",
        "onb.welcome.cta": "Get Started",
        "onb.lang.title": "Choose your language",
        "onb.lang.subtitle": "Interface language. You can change it anytime in Settings.",
        "onb.welcome.title": "Welcome to Ember",
        "onb.welcome.subtitle": "Meeting transcription and summaries — entirely on your device. Set up in a minute.",
        "onb.welcome.f1": "Local & private",
        "onb.welcome.f1sub": "Audio and text never leave your Mac",
        "onb.welcome.f2": "Works offline",
        "onb.welcome.f2sub": "Models run right on your device",
        "onb.welcome.f3": "Export to Markdown",
        "onb.welcome.f3sub": "Summaries are ready for Obsidian",
        "onb.summary.title": "Summary model",
        "onb.summary.subtitle": "A local AI model that turns the transcript into a structured summary. You can change it anytime in Settings.",
        "onb.whisper.title": "Speech recognition model",
        "onb.whisper.subtitle": "Whisper turns audio into text. Larger models are more accurate but heavier.",
        "onb.perm.title": "Sound access",
        "onb.perm.subtitle": "Ember needs the microphone and system audio to record meetings. Audio is processed locally.",
        "onb.perm.mic": "Microphone",
        "onb.perm.micDesc": "To record your voice.",
        "onb.perm.system": "System audio",
        "onb.perm.systemDesc": "To record other participants.",
        "onb.perm.granted": "Granted",
        "onb.perm.note": "macOS will show a system dialog. Confirm access in Settings → Privacy.",
        "onb.perm.finish": "Finish",
        "onb.perm.skip": "Skip for now",
        "onb.perm.allow": "Allow",
        "onb.perm.open": "Open Settings",
        "model.ready": "Ready",
        "model.selected": "Selected",
        "model.select": "Select",
        "model.download": "Download",
        "model.downloading": "Downloading {p}",
        "model.failed": "Download failed",
        "model.retry": "Retry",
        "model.ramHint": "Needs ~{g} GB RAM",
        "model.qwen2507.desc": "Updated Qwen3 4B: newer instruct weights + distilled quantization — noticeably more accurate at the same RAM and speed",
        "model.dwq.desc": "Same model, distilled quantization — noticeably closer to full quality at the same RAM and speed",
        "model.gigaam.desc": "Excellent for Russian — 2-3× more accurate than Whisper. Russian only, no punctuation",
        "model.tokens": "tokens",
        "meeting.transcript": "Transcript",
        "meeting.summary": "Summary",
        "meeting.copy": "Copy",
        "meeting.regenerate": "Regenerate",
        "meeting.model": "Model",
        "meeting.generating": "Generating summary…",
        "meeting.noSummary": "No summary yet",
        "meeting.noSummaryDesc": "Ember will analyze the transcript and prepare a TL;DR, decisions and tasks.",
        "meeting.generate": "Generate summary",
        "meeting.savedMd": "Saved as Markdown",
        "meeting.export": "Export",
        "meeting.renameHint": "Double-click to rename",
        "meeting.openObsidian": "Open in Obsidian →",
        "meeting.openSage": "Open in Sage",
        "meeting.participants": "participants",
        "meeting.processing": "Transcribing…",
        "processing.step": "Step {n} of {t}",
        "processing.stage.transcribe": "Refining the transcript…",
        "processing.stage.summarize": "Writing the summary…",
        "settings.tab.general": "General",
        "settings.tab.recording": "Recording",
        "settings.tab.transcription": "Transcription",
        "settings.tab.summary": "Summary",
        "settings.tab.updates": "Updates",
        "settings.theme": "Theme",
        "settings.theme.light": "Light",
        "settings.theme.dark": "Dark",
        "settings.theme.auto": "Auto",
        "settings.language": "Interface language",
        "settings.autoSummary": "Auto-generate summary after recording",
        "settings.notifications": "System notifications",
        "settings.group.appearance": "Appearance",
        "settings.group.system": "System",
        "settings.launchAtLogin": "Launch at login",
        "settings.launchAtLogin.desc": "Ember starts automatically after you log in to your Mac — call auto-detection is armed right away.",
        "settings.launchAtLogin.approve": "Allow Ember in System Settings → Login Items",
        "settings.group.notifications": "Notifications",
        "settings.group.data": "Data & export",
        "settings.group.calendar": "Calendar",
        "settings.calendar": "Meeting titles from Calendar",
        "settings.calendar.desc": "If a calendar event is in progress when a recording starts, its name becomes the meeting title. Without an event the AI names the meeting as usual. Ember reads the calendar only at recording start.",
        "settings.calendar.granted": "Calendar access granted",
        "settings.calendar.denied": "Access denied — allow it in System Settings",
        "settings.calendar.open": "Open System Settings",
        "settings.summary.title": "Summary model (local)",
        "settings.transcription.title": "Speech recognition model",
        "settings.recording.note": "Microphone and system audio are captured automatically while recording.",
        "settings.version": "Version",
        "settings.checkUpdates": "Check for updates",
        "settings.upToDate": "Ember is up to date",
        "settings.autoUpdate": "Check for updates automatically",
        "update.checking": "Checking for updates…",
        "update.available": "Version {v} is available",
        "update.downloading": "Downloading… {p}%",
        "update.readyToInstall": "Version {v} is ready",
        "update.restart": "Restart to update",
        "update.download": "Download",
        "update.err.network": "Couldn't reach the update server",
        "update.err.checksum": "Downloaded update failed verification",
        "update.err.missingChecksum": "Update has no checksum — refusing to install for safety",
        "update.err.translocated": "Move Ember to /Applications and relaunch to update",
        "update.err.noApp": "Update archive is invalid",
        "update.err.install": "Couldn't install the update",
        "update.notify": "Version {v} is available — open Settings → Updates",
        "settings.theme.desc": "App appearance",
        "settings.accent": "Accent color",
        "settings.accent.desc": "Tint of buttons, highlights and selection",
        "settings.language.desc": "App language. Speech recognition is configured separately in the Recognition tab.",
        "settings.dataFolder": "App data",
        "settings.notifications.desc": "Show notifications when recording starts and stops",
        "settings.autoSummary.desc": "When off, no summary is created automatically — you can generate one manually from the meeting.",
        "common.choose": "Choose",
        "common.open": "Open",
        "settings.exportFolder": "Export summaries to Markdown",
        "settings.exportFolder.desc": "Folder where meeting summary .md files are saved on export, grouped into per-day subfolders (01.02.2026).",
        "settings.dataLocation": "Data location",
        "settings.recordingsFolder": "Meeting recordings",
        "settings.recording.notifyOnStart": "Recording-start reminder",
        "settings.recording.notifyOnStart.desc": "Show a reminder to tell participants that recording has started.",
        "settings.recording.deferred": "Defer processing during calls",
        "settings.recording.deferred.desc": "Works together with auto-summary: if the next call starts right after one ends, "
            + "transcription and summary wait in a queue and run once ALL calls are over — the Mac stays cool and quiet while "
            + "you talk, the live transcript works as usual. Audio of finished calls is kept temporarily in the app cache and "
            + "deleted right after processing — also on quit or crash. With auto-summary off there is nothing to defer, so this "
            + "switch is disabled.",
        "settings.group.processing": "Processing",
        "settings.group.devices": "Audio devices",
        "processing.queuePosition": "In queue: {n} of {t}",
        "processing.stage.queued": "Waiting for calls to finish…",
        "toast.recQueued": "Recording queued — processing after your calls",
        "settings.recording.devices": "Audio devices",
        "settings.recording.devices.desc": "Choose the preferred microphone and system-audio device. They are selected automatically when new recordings start.",
        "settings.recording.microphone": "Microphone",
        "settings.recording.systemAudio": "System audio",
        "settings.recording.micDefault": "Default microphone",
        "settings.recording.systemDefault": "Default system audio",
        "settings.recording.micNote": "Microphone: records your voice and surrounding sounds",
        "settings.recording.sysNote": "System audio: records sound from the computer (music, calls, etc.)",
        "toast.recStarted": "Recording started",
        "toast.recReminder": "Recording started — let participants know",
        "toast.micDenied": "Microphone access denied — enable it in System Settings",
        "toast.micSilent": "No sound from the microphone — check the input device in Settings",
        "toast.recStopped": "Recording stopped — processing…",
        "toast.summaryReady": "Summary ready",
        "toast.summaryFailed": "Couldn't generate the summary",
        "toast.summaryLowMemory": "Not enough memory for this model — pick a smaller one",
        "toast.recFailed": "Couldn't start recording",
        "toast.transcribeFailed": "Couldn't transcribe the recording",
        "toast.exportFailed": "Couldn't save the Markdown file",
        "toast.persistenceDegraded": "Storage unavailable — meetings won't be saved",
        "toast.autoDiscarded": "False auto-start detected — recording discarded",
        "speaker.me": "Me",
        "speaker.them": "Speaker",
        "speaker.me.short": "Me",
        "speaker.them.short": "S",
        "dialog.rename.title": "Rename meeting",
        "dialog.delete.title": "Delete meeting?",
        "dialog.delete.msg": "The transcript, summary and audio will be deleted. This cannot be undone.",
        "settings.model.delete": "Delete from disk",
        "dialog.deleteModel.title": "Delete model?",
        "dialog.deleteModel.msg": "{name} ({size}) will be removed from disk. You can download it again anytime.",
        "settings.deepseek.title": "DeepSeek API (optional)",
        "settings.deepseek.desc": "With a key, summaries are generated via DeepSeek — the transcript is sent to DeepSeek's servers. If it's unavailable, the local model takes over automatically.",
        "settings.deepseek.placeholder": "sk-…",
        "settings.deepseek.save": "Verify & save",
        "settings.deepseek.checking": "Checking…",
        "settings.deepseek.valid": "Key active",
        "settings.deepseek.invalid": "Key didn't work — check it and try again",
        "settings.deepseek.unavailable": "DeepSeek is unreachable right now — the local fallback is in effect",
        "settings.deepseek.delete": "Delete key",
        "settings.deepseek.model": "Model",
        "toast.deepseekFellBack": "DeepSeek unavailable — using the local model",
        "settings.template.title": "Summary template",
        "settings.template.desc": "The template shapes how summaries are written. Standard.md and your own templates live in a folder you can edit by hand — changes are picked up automatically.",
        "settings.template.picker": "Default template",
        "settings.template.open": "Open folder",
        "settings.template.restore": "Restore standard",
        "settings.template.imported": "Template imported — pick it as the default when you want it",
        "settings.template.importFailed": "Couldn't import the template",
        "common.import": "Import…",
        "whatsnew.title": "What's new in {v}",
        "whatsnew.ok": "Got it",
        "ctx.rename": "Rename",
        "ctx.delete": "Delete"
    ]

    static let ru: [String: String] = [
        "app.name": "Ember",
        "menubar.start": "Начать запись",
        "menubar.pause": "Пауза записи",
        "menubar.resume": "Продолжить запись",
        "menubar.stop": "Остановить запись",
        "menubar.settings": "Настройки",
        "menubar.show": "Показать Ember",
        "menubar.quit": "Выйти из Ember",
        "model.badge.recommended": "Рекомендуем",
        "editor.blkH1": "Заголовок 1",
        "editor.blkH2": "Заголовок 2",
        "editor.blkH3": "Заголовок 3",
        "dialog.regenEdited.title": "Перезаписать правки?",
        "dialog.regenEdited.msg": "Саммари было отредактировано вручную — перегенерация заменит его новым текстом ИИ.",
        "models.group.russian": "Русская речь (GigaAM)",
        "models.group.multilingual": "Многоязычные (Whisper)",
        "models.group.light": "Лёгкие — 1.7B",
        "models.group.standard": "Основные — 4B",
        "models.group.max": "Старшие — 8B",
        "model.badge.balanced": "Баланс",
        "nav.home": "Главная",
        "nav.meetings": "Встречи",
        "nav.settings": "Настройки",
        "common.back": "Назад",
        "common.continue": "Продолжить",
        "common.cancel": "Отмена",
        "common.done": "Готово",
        "common.save": "Сохранить",
        "common.delete": "Удалить",
        "common.retry": "Повторить",
        "common.dismiss": "Закрыть",
        "home.ready.title": "Готов к записи",
        "home.ready.subtitle": "Начните запись — транскрипт появится здесь в реальном времени.",
        "home.empty.title": "Запишите первую встречу",
        "home.empty.subtitle": "Нажмите, чтобы начать. Ember расшифрует речь и подготовит саммари — всё локально.",
        "home.shortcut": "⌘R   чтобы начать",
        "recording.status": "Идёт запись",
        "transcript.live": "Транскрипт · в реальном времени",
        "transcript.listening": "Распознаю…",
        "settings.title": "Настройки",
        "sidebar.search": "Поиск по встречам",
        "sidebar.today": "Сегодня",
        "sidebar.yesterday": "Вчера",
        "sidebar.meetings": "Встречи",
        "sidebar.empty1": "Пока нет встреч.",
        "sidebar.empty2": "Начните первую запись.",
        "sidebar.noResults": "Ничего не найдено. Измените запрос.",
        "meeting.exportType": "Встреча",
        "common.next": "Далее",
        "common.getStarted": "Начать",
        "onb.step": "шаг {n} из {t}",
        "onb.welcome.cta": "Начать настройку",
        "onb.lang.title": "Выберите язык",
        "onb.lang.subtitle": "Язык интерфейса. Сменить можно в любой момент в настройках.",
        "onb.welcome.title": "Добро пожаловать в Ember",
        "onb.welcome.subtitle": "Транскрипция и саммари встреч — полностью на вашем устройстве. Настроим за минуту.",
        "onb.welcome.f1": "Локально и приватно",
        "onb.welcome.f1sub": "Аудио и текст не покидают компьютер",
        "onb.welcome.f2": "Работает без интернета",
        "onb.welcome.f2sub": "Модели запускаются прямо на устройстве",
        "onb.welcome.f3": "Экспорт в Markdown",
        "onb.welcome.f3sub": "Саммари сразу готовы для Obsidian",
        "onb.summary.title": "Модель для конспектов",
        "onb.summary.subtitle": "Локальная ИИ-модель, которая превращает транскрипт в структурированное саммари. Выбрать можно в любой момент в настройках.",
        "onb.whisper.title": "Модель распознавания речи",
        "onb.whisper.subtitle": "Whisper расшифровывает аудио в текст. Чем крупнее модель — тем выше точность и нагрузка.",
        "onb.perm.title": "Доступ к звуку",
        "onb.perm.subtitle": "Ember нужен микрофон и системный звук, чтобы записывать встречи. Аудио обрабатывается локально.",
        "onb.perm.mic": "Микрофон",
        "onb.perm.micDesc": "Для записи вашего голоса.",
        "onb.perm.system": "Системный звук",
        "onb.perm.systemDesc": "Для записи речи собеседников.",
        "onb.perm.granted": "Разрешено",
        "onb.perm.note": "macOS откроет системный диалог. Подтвердите доступ в «Настройки → Конфиденциальность».",
        "onb.perm.finish": "Готово",
        "onb.perm.skip": "Пропустить",
        "onb.perm.allow": "Разрешить",
        "onb.perm.open": "Открыть настройки",
        "model.ready": "Готова",
        "model.selected": "Выбрана",
        "model.select": "Выбрать",
        "model.download": "Скачать",
        "model.downloading": "Скачивание {p}",
        "model.failed": "Ошибка загрузки",
        "model.retry": "Повторить",
        "model.ramHint": "Нужно ~{g} ГБ RAM",
        "model.qwen2507.desc": "Обновлённый Qwen3 4B: свежие instruct-веса + дистиллированное квантование — заметно точнее при той же памяти и скорости",
        "model.dwq.desc": "Та же модель с дистиллированным квантованием — заметно ближе к полному качеству при той же памяти и скорости",
        "model.gigaam.desc": "Отлично подходит для русского — в 2-3 раза точнее Whisper. Только русский язык, без пунктуации",
        "model.tokens": "токенов",
        "meeting.transcript": "Транскрипт",
        "meeting.summary": "Саммари",
        "meeting.copy": "Копировать",
        "meeting.regenerate": "Перегенерировать",
        "meeting.model": "Модель",
        "meeting.generating": "Готовлю саммари…",
        "meeting.noSummary": "Саммари ещё не создано",
        "meeting.noSummaryDesc": "Ember проанализирует транскрипт и подготовит краткое содержание, решения и задачи.",
        "meeting.generate": "Сгенерировать саммари",
        "meeting.savedMd": "Сохранено в Markdown",
        "meeting.export": "Экспорт",
        "meeting.renameHint": "Двойной клик — переименовать",
        "meeting.openObsidian": "Открыть в Obsidian →",
        "meeting.openSage": "Открыть в Sage",
        "meeting.participants": "участников",
        "meeting.processing": "Распознаю…",
        "processing.step": "Шаг {n} из {t}",
        "processing.stage.transcribe": "Уточняю транскрипт…",
        "processing.stage.summarize": "Пишу саммари…",
        "settings.tab.general": "Общие",
        "settings.tab.recording": "Запись",
        "settings.tab.transcription": "Распознавание",
        "settings.tab.summary": "Саммари",
        "settings.tab.updates": "Обновления",
        "settings.theme": "Тема",
        "settings.theme.light": "Светлая",
        "settings.theme.dark": "Тёмная",
        "settings.theme.auto": "Авто",
        "settings.language": "Язык интерфейса",
        "settings.autoSummary": "Автоматически создавать саммари после записи",
        "settings.notifications": "Системные уведомления",
        "settings.group.appearance": "Оформление",
        "settings.group.system": "Система",
        "settings.launchAtLogin": "Запускать при входе в macOS",
        "settings.launchAtLogin.desc": "Ember откроется сам после входа в систему — автозапись звонков будет наготове сразу.",
        "settings.launchAtLogin.approve": "Разрешите Ember в Настройках системы → Объекты входа",
        "settings.group.notifications": "Уведомления",
        "settings.group.data": "Данные и экспорт",
        "settings.group.calendar": "Календарь",
        "settings.calendar": "Названия встреч из Календаря",
        "settings.calendar.desc": "Если в момент начала записи в Календаре идёт встреча — её название станет названием встречи в Ember. Без события название придумает ИИ, как обычно. Ember читает календарь только в момент старта записи.",
        "settings.calendar.granted": "Доступ к Календарю есть",
        "settings.calendar.denied": "Доступ запрещён — разрешите в Системных настройках",
        "settings.calendar.open": "Открыть Системные настройки",
        "settings.summary.title": "Модель саммари (локальная)",
        "settings.transcription.title": "Модель распознавания речи",
        "settings.recording.note": "Микрофон и системный звук захватываются автоматически во время записи.",
        "settings.version": "Версия",
        "settings.checkUpdates": "Проверить обновления",
        "settings.upToDate": "Ember в актуальной версии",
        "settings.autoUpdate": "Проверять обновления автоматически",
        "update.checking": "Проверка обновлений…",
        "update.available": "Доступна версия {v}",
        "update.downloading": "Загрузка… {p}%",
        "update.readyToInstall": "Версия {v} готова к установке",
        "update.restart": "Перезапустить и обновить",
        "update.download": "Загрузить",
        "update.err.network": "Не удалось связаться с сервером обновлений",
        "update.err.checksum": "Загруженное обновление не прошло проверку",
        "update.err.missingChecksum": "У обновления нет контрольной суммы — установка отменена для безопасности",
        "update.err.translocated": "Перенесите Ember в /Applications и перезапустите для обновления",
        "update.err.noApp": "Архив обновления повреждён",
        "update.err.install": "Не удалось установить обновление",
        "update.notify": "Доступна версия {v} — откройте Настройки → Обновления",
        "settings.theme.desc": "Внешний вид приложения",
        "settings.accent": "Акцентный цвет",
        "settings.accent.desc": "Цвет кнопок, подсветок и выделений",
        "settings.language.desc": "Язык приложения. Распознавание речи настраивается отдельно во вкладке «Распознавание».",
        "settings.dataFolder": "Данные приложения",
        "settings.notifications.desc": "Показывать уведомления о начале и конце записи",
        "settings.autoSummary.desc": "Если выключено — саммари не создаётся автоматически; его можно сгенерировать вручную в карточке встречи.",
        "common.choose": "Выбрать",
        "common.open": "Открыть",
        "settings.exportFolder": "Экспорт саммари в Markdown",
        "settings.exportFolder.desc": "Папка, куда сохраняются файлы .md при экспорте саммари — внутри раскладываются по папкам дат (01.02.2026).",
        "settings.dataLocation": "Расположение данных",
        "settings.recordingsFolder": "Записи встреч",
        "settings.recording.notifyOnStart": "Уведомление о начале записи",
        "settings.recording.notifyOnStart.desc": "Показывать напоминание сообщить участникам о начале записи.",
        "settings.recording.deferred": "Отложенная обработка после звонков",
        "settings.recording.deferred.desc": "Работает в паре с автосаммари: если сразу после звонка начинается следующий — "
            + "расшифровка и саммари ждут в очереди и запускаются, когда ВСЕ звонки закончились: мак не шумит и не тормозит "
            + "во время разговора, живой транскрипт работает как обычно. Аудио завершённых звонков временно хранится в кэше "
            + "приложения и удаляется сразу после обработки — при выходе или сбое тоже. Если автосаммари выключено, "
            + "откладывать нечего — тумблер неактивен.",
        "settings.group.processing": "Обработка",
        "settings.group.devices": "Аудиоустройства",
        "processing.queuePosition": "В очереди: {n} из {t}",
        "processing.stage.queued": "Жду окончания звонков…",
        "toast.recQueued": "Запись в очереди — обработаю после звонков",
        "settings.recording.devices": "Аудиоустройства",
        "settings.recording.devices.desc": "Выберите предпочитаемые микрофон и устройство системного звука. Они будут выбраны автоматически при запуске новых записей.",
        "settings.recording.microphone": "Микрофон",
        "settings.recording.systemAudio": "Системный звук",
        "settings.recording.micDefault": "Микрофон по умолчанию",
        "settings.recording.systemDefault": "Системный звук по умолчанию",
        "settings.recording.micNote": "Микрофон: записывает ваш голос и звуки вокруг",
        "settings.recording.sysNote": "Системный звук: записывает звук с компьютера (музыка, звонки и т.д.)",
        "toast.recStarted": "Запись началась",
        "toast.recReminder": "Идёт запись — предупредите участников",
        "toast.micDenied": "Доступ к микрофону запрещён — включите в Системных настройках",
        "toast.micSilent": "Нет звука с микрофона — проверьте устройство ввода в Настройках",
        "toast.recStopped": "Запись остановлена — обработка…",
        "toast.summaryReady": "Саммари готово",
        "toast.summaryFailed": "Не удалось сгенерировать саммари",
        "toast.summaryLowMemory": "Недостаточно памяти для этой модели — выберите меньше",
        "toast.recFailed": "Не удалось начать запись",
        "toast.transcribeFailed": "Не удалось распознать запись",
        "toast.exportFailed": "Не удалось сохранить Markdown-файл",
        "toast.persistenceDegraded": "Хранилище недоступно — встречи не сохранятся",
        "toast.autoDiscarded": "Похоже, ложный автостарт — запись отброшена",
        "speaker.me": "Я",
        "speaker.them": "Собеседник",
        "speaker.me.short": "Я",
        "speaker.them.short": "С",
        "dialog.rename.title": "Переименовать встречу",
        "dialog.delete.title": "Удалить встречу?",
        "dialog.delete.msg": "Будут удалены транскрипт, саммари и аудио. Действие необратимо.",
        "settings.model.delete": "Удалить с диска",
        "dialog.deleteModel.title": "Удалить модель?",
        "dialog.deleteModel.msg": "«{name}» ({size}) будет удалена с диска. Её можно скачать заново в любой момент.",
        "settings.deepseek.title": "DeepSeek API (опционально)",
        "settings.deepseek.desc": "С ключом саммари генерируется через DeepSeek — транскрипт отправляется на серверы DeepSeek. Если он недоступен, автоматически работает локальная модель.",
        "settings.deepseek.placeholder": "sk-…",
        "settings.deepseek.save": "Проверить и сохранить",
        "settings.deepseek.checking": "Проверяю…",
        "settings.deepseek.valid": "Ключ активен",
        "settings.deepseek.invalid": "Ключ не сработал — проверьте и попробуйте снова",
        "settings.deepseek.unavailable": "DeepSeek сейчас недоступен — работает локальный фолбек",
        "settings.deepseek.delete": "Удалить ключ",
        "settings.deepseek.model": "Модель",
        "toast.deepseekFellBack": "DeepSeek недоступен — саммари локальной моделью",
        "settings.template.title": "Шаблон саммари",
        "settings.template.desc": "Шаблон задаёт, как пишется саммари. Standard.md и ваши шаблоны лежат в папке — их можно править вручную, изменения подхватываются автоматически.",
        "settings.template.picker": "Шаблон по умолчанию",
        "settings.template.open": "Открыть папку",
        "settings.template.restore": "Восстановить стандартный",
        "settings.template.imported": "Шаблон импортирован — выберите его дефолтным, когда нужно",
        "settings.template.importFailed": "Не удалось импортировать шаблон",
        "common.import": "Импорт…",
        "whatsnew.title": "Что нового в {v}",
        "whatsnew.ok": "Понятно",
        "ctx.rename": "Переименовать",
        "ctx.delete": "Удалить"
    ]
}

extension LocalizedStrings {
    static let zh: [String: String] = [
        "app.name": "Ember",
        "menubar.start": "开始录制",
        "menubar.pause": "暂停录音",
        "menubar.resume": "继续录音",
        "menubar.stop": "停止录制",
        "menubar.settings": "设置",
        "menubar.show": "显示 Ember",
        "menubar.quit": "退出 Ember",
        "model.badge.recommended": "推荐",
        "editor.blkH1": "一级标题",
        "editor.blkH2": "二级标题",
        "editor.blkH3": "三级标题",
        "dialog.regenEdited.title": "覆盖你的修改？",
        "dialog.regenEdited.msg": "此摘要已手动编辑——重新生成将用全新的 AI 文本替换它。",
        "models.group.russian": "俄语语音（GigaAM）",
        "models.group.multilingual": "多语言（Whisper）",
        "models.group.light": "轻量 — 1.7B",
        "models.group.standard": "主力 — 4B",
        "models.group.max": "旗舰 — 8B",
        "model.badge.balanced": "均衡",
        "nav.home": "主页",
        "nav.meetings": "会议",
        "nav.settings": "设置",
        "common.back": "返回",
        "common.continue": "继续",
        "common.cancel": "取消",
        "common.done": "完成",
        "common.save": "保存",
        "common.delete": "删除",
        "common.retry": "重试",
        "common.dismiss": "关闭",
        "home.ready.title": "准备录制",
        "home.ready.subtitle": "开始录制——文字记录将实时显示在这里。",
        "home.empty.title": "录制你的第一场会议",
        "home.empty.subtitle": "点击开始。Ember 会转写语音并生成摘要——全部在本地完成。",
        "home.shortcut": "⌘R   开始",
        "recording.status": "正在录制",
        "transcript.live": "文字记录 · 实时",
        "transcript.listening": "正在识别…",
        "settings.title": "设置",
        "sidebar.search": "搜索会议",
        "sidebar.today": "今天",
        "sidebar.yesterday": "昨天",
        "sidebar.meetings": "会议",
        "sidebar.empty1": "暂无会议。",
        "sidebar.empty2": "开始第一次录音。",
        "sidebar.noResults": "未找到结果，请尝试其他关键词。",
        "meeting.exportType": "会议",
        "common.next": "下一步",
        "common.getStarted": "开始",
        "onb.step": "第 {n} 步，共 {t} 步",
        "onb.welcome.cta": "开始设置",
        "onb.lang.title": "选择语言",
        "onb.lang.subtitle": "界面语言。可随时在设置中更改。",
        "onb.welcome.title": "欢迎使用 Ember",
        "onb.welcome.subtitle": "会议转写与摘要——完全在你的设备上完成。一分钟即可设置。",
        "onb.welcome.f1": "本地且私密",
        "onb.welcome.f1sub": "音频和文字绝不离开你的电脑",
        "onb.welcome.f2": "离线可用",
        "onb.welcome.f2sub": "模型直接在设备上运行",
        "onb.welcome.f3": "导出到 Markdown",
        "onb.welcome.f3sub": "摘要可直接用于 Obsidian",
        "onb.summary.title": "摘要模型",
        "onb.summary.subtitle": "本地 AI 模型，把转写整理成结构化摘要。可随时在设置中更改。",
        "onb.whisper.title": "语音识别模型",
        "onb.whisper.subtitle": "Whisper 把音频转成文字。模型越大越准确，但更占资源。",
        "onb.perm.title": "声音访问",
        "onb.perm.subtitle": "Ember 需要麦克风和系统声音来录制会议。音频在本地处理。",
        "onb.perm.mic": "麦克风",
        "onb.perm.micDesc": "用于录制你的声音。",
        "onb.perm.system": "系统声音",
        "onb.perm.systemDesc": "用于录制其他参与者。",
        "onb.perm.granted": "已允许",
        "onb.perm.note": "macOS 将弹出系统对话框。请在「设置 → 隐私与安全性」中确认访问。",
        "onb.perm.finish": "完成",
        "onb.perm.skip": "暂时跳过",
        "onb.perm.allow": "允许",
        "onb.perm.open": "打开设置",
        "model.ready": "已就绪",
        "model.selected": "已选择",
        "model.select": "选择",
        "model.download": "下载",
        "model.downloading": "下载中 {p}",
        "model.failed": "下载失败",
        "model.retry": "重试",
        "model.ramHint": "需要约 {g} GB 内存",
        "model.qwen2507.desc": "升级版 Qwen3 4B：更新的指令权重 + 蒸馏量化——同等内存和速度下明显更准确",
        "model.dwq.desc": "同一模型的蒸馏量化版——同等内存和速度下明显更接近完整精度",
        "model.gigaam.desc": "俄语最佳选择——比 Whisper 准确 2-3 倍。仅支持俄语，无标点",
        "model.tokens": "个 token",
        "meeting.transcript": "转写",
        "meeting.summary": "摘要",
        "meeting.copy": "复制",
        "meeting.regenerate": "重新生成",
        "meeting.model": "模型",
        "meeting.generating": "正在生成摘要…",
        "meeting.noSummary": "尚未生成摘要",
        "meeting.noSummaryDesc": "Ember 将分析转写并准备要点、决策与任务。",
        "meeting.generate": "生成摘要",
        "meeting.savedMd": "已保存为 Markdown",
        "meeting.export": "导出",
        "meeting.renameHint": "双击重命名",
        "meeting.openObsidian": "在 Obsidian 中打开 →",
        "meeting.openSage": "在 Sage 中打开",
        "meeting.participants": "位参与者",
        "meeting.processing": "转写中…",
        "processing.step": "第 {n} 步，共 {t} 步",
        "processing.stage.transcribe": "正在校对转写…",
        "processing.stage.summarize": "正在生成摘要…",
        "settings.tab.general": "通用",
        "settings.tab.recording": "录音",
        "settings.tab.transcription": "识别",
        "settings.tab.summary": "摘要",
        "settings.tab.updates": "更新",
        "settings.theme": "主题",
        "settings.theme.light": "浅色",
        "settings.theme.dark": "深色",
        "settings.theme.auto": "自动",
        "settings.language": "界面语言",
        "settings.autoSummary": "录制后自动生成摘要",
        "settings.notifications": "系统通知",
        "settings.group.appearance": "外观",
        "settings.group.system": "系统",
        "settings.launchAtLogin": "登录时启动",
        "settings.launchAtLogin.desc": "登录 Mac 后 Ember 自动启动——通话自动录制随即待命。",
        "settings.launchAtLogin.approve": "请在 系统设置 → 登录项 中允许 Ember",
        "settings.group.notifications": "通知",
        "settings.group.data": "数据与导出",
        "settings.group.calendar": "日历",
        "settings.calendar": "会议标题取自日历",
        "settings.calendar.desc": "若录音开始时日历中有正在进行的事件，其名称将成为会议标题；没有事件时照常由 AI 命名。Ember 仅在录音开始时读取日历。",
        "settings.calendar.granted": "已获得日历访问权限",
        "settings.calendar.denied": "访问被拒 — 请在系统设置中允许",
        "settings.calendar.open": "打开系统设置",
        "settings.summary.title": "摘要模型（本地）",
        "settings.transcription.title": "语音识别模型",
        "settings.recording.note": "录制时自动采集麦克风与系统声音。",
        "settings.version": "版本",
        "settings.checkUpdates": "检查更新",
        "settings.upToDate": "Ember 已是最新版本",
        "settings.autoUpdate": "自动检查更新",
        "update.checking": "正在检查更新…",
        "update.available": "有新版本 {v}",
        "update.downloading": "下载中… {p}%",
        "update.readyToInstall": "版本 {v} 已就绪",
        "update.restart": "重启以更新",
        "update.download": "下载",
        "update.err.network": "无法连接更新服务器",
        "update.err.checksum": "下载的更新校验失败",
        "update.err.missingChecksum": "更新缺少校验和——为安全起见已拒绝安装",
        "update.err.translocated": "请将 Ember 移到 /Applications 并重启以更新",
        "update.err.noApp": "更新包无效",
        "update.err.install": "无法安装更新",
        "update.notify": "有新版本 {v}——打开 设置 → 更新",
        "settings.theme.desc": "应用外观",
        "settings.accent": "强调色",
        "settings.accent.desc": "按钮、高亮与选中状态的颜色",
        "settings.language.desc": "应用语言。语音识别在「识别」选项卡中单独设置。",
        "settings.dataFolder": "应用数据",
        "settings.notifications.desc": "在录制开始和结束时显示通知",
        "settings.autoSummary.desc": "关闭后不会自动生成摘要——可在会议详情中手动生成。",
        "common.choose": "选择",
        "common.open": "打开",
        "settings.exportFolder": "导出摘要为 Markdown",
        "settings.exportFolder.desc": "导出会议摘要时 .md 文件的保存文件夹，按日期子文件夹（01.02.2026）归档。",
        "settings.dataLocation": "数据位置",
        "settings.recordingsFolder": "会议录音",
        "settings.recording.notifyOnStart": "录制开始提醒",
        "settings.recording.notifyOnStart.desc": "显示提醒，告知参会者录制已开始。",
        "settings.recording.deferred": "通话期间延后处理",
        "settings.recording.deferred.desc": "与自动摘要配合使用：若通话一个接一个，转写和摘要会排队等所有通话结束后再运行——通话期间 Mac 保持安静流畅，实时转写照常工作。已结束通话的音频临时存于应用缓存，处理后立即删除；退出或崩溃时同样删除。关闭自动摘要时无可延后内容，此开关不可用。",
        "settings.group.processing": "处理",
        "settings.group.devices": "音频设备",
        "processing.queuePosition": "排队第 {n}/{t} 位",
        "processing.stage.queued": "等待通话结束…",
        "toast.recQueued": "录音已排队——通话结束后处理",
        "settings.recording.devices": "音频设备",
        "settings.recording.devices.desc": "选择首选的麦克风和系统音频设备。开始新录制时将自动使用。",
        "settings.recording.microphone": "麦克风",
        "settings.recording.systemAudio": "系统音频",
        "settings.recording.micDefault": "默认麦克风",
        "settings.recording.systemDefault": "默认系统音频",
        "settings.recording.micNote": "麦克风：录制你的声音和周围声音",
        "settings.recording.sysNote": "系统音频：录制电脑发出的声音（音乐、通话等）",
        "toast.recStarted": "开始录音",
        "toast.recReminder": "正在录音——请告知参会者",
        "toast.micDenied": "麦克风访问被拒绝——请在系统设置中开启",
        "toast.micSilent": "麦克风没有声音——请在设置中检查输入设备",
        "toast.recStopped": "录音已停止——处理中…",
        "toast.summaryReady": "摘要已就绪",
        "toast.summaryFailed": "无法生成摘要",
        "toast.summaryLowMemory": "内存不足，无法运行此模型——请选择更小的模型",
        "toast.recFailed": "无法开始录音",
        "toast.transcribeFailed": "无法转写录音",
        "toast.exportFailed": "无法保存 Markdown 文件",
        "toast.persistenceDegraded": "存储不可用——会议将不会被保存",
        "toast.autoDiscarded": "疑似误触发自动录制——已丢弃",
        "speaker.me": "我",
        "speaker.them": "对方",
        "speaker.me.short": "我",
        "speaker.them.short": "对",
        "dialog.rename.title": "重命名会议",
        "dialog.delete.title": "删除会议？",
        "settings.model.delete": "从磁盘删除",
        "dialog.deleteModel.title": "删除模型？",
        "dialog.deleteModel.msg": "「{name}」（{size}）将从磁盘中删除。可随时重新下载。",
        "settings.deepseek.title": "DeepSeek API（可选）",
        "settings.deepseek.desc": "填写密钥后，摘要将通过 DeepSeek 生成——转写内容会发送到 DeepSeek 服务器。若不可用，将自动使用本地模型。",
        "settings.deepseek.placeholder": "sk-…",
        "settings.deepseek.save": "验证并保存",
        "settings.deepseek.checking": "正在检查…",
        "settings.deepseek.valid": "密钥有效",
        "settings.deepseek.invalid": "密钥无效——请检查后重试",
        "settings.deepseek.unavailable": "DeepSeek 当前不可用——已启用本地回退",
        "settings.deepseek.delete": "删除密钥",
        "settings.deepseek.model": "模型",
        "toast.deepseekFellBack": "DeepSeek 不可用——使用本地模型生成摘要",
        "settings.template.title": "摘要模板",
        "settings.template.desc": "模板决定摘要的写法。Standard.md 和你自己的模板都放在一个文件夹里，可手动编辑，改动会自动生效。",
        "settings.template.picker": "默认模板",
        "settings.template.open": "打开文件夹",
        "settings.template.restore": "恢复标准模板",
        "settings.template.imported": "模板已导入——需要时可将其设为默认",
        "settings.template.importFailed": "无法导入模板",
        "common.import": "导入…",
        "whatsnew.title": "{v} 的新变化",
        "whatsnew.ok": "知道了",
        "dialog.delete.msg": "转写、摘要和音频都将被删除。此操作无法撤销。",
        "ctx.rename": "重命名",
        "ctx.delete": "删除"
    ]
}
